---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lqf.
--- DateTime: 2022/4/17 14:59
---
if redis.call("GET",KEYS[1])==ARGV[1] then
    return redis.call("DEL",KEYS[1])
else
    return 0
end