<<<<<<< HEAD
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lqf.
--- DateTime: 2022/4/17 14:59
---

if redis.call("GET",KEYS[1])==ARGV[1] then
    redis.call("expire",KEYS[1],ARGV[2])
    return "ok"
else
    return redis.call("SET",KEYS[1],ARGV[1],"NX","EX",ARGV[2])
=======
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lqf.
--- DateTime: 2022/4/17 14:59
---

if redis.call("GET",KEYS[1])==ARGV[1] then
    redis.call("expire",KEYS[1],ARGV[2])
    return "ok"
else
    return redis.call("SET",KEYS[1],ARGV[1],"NX","EX",ARGV[2])
>>>>>>> master
end