// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: example.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A         int32   `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	P         int32   `protobuf:"zigzag32,2,opt,name=p,proto3" json:"p,omitempty"`
	Pp        int64   `protobuf:"varint,3,opt,name=pp,proto3" json:"pp,omitempty"`
	Ppp       int64   `protobuf:"zigzag64,4,opt,name=ppp,proto3" json:"ppp,omitempty"`
	Name      string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Namess    []byte  `protobuf:"bytes,6,opt,name=namess,proto3" json:"namess,omitempty"`
	Doub      float64 `protobuf:"fixed64,7,opt,name=doub,proto3" json:"doub,omitempty"`
	Floa      float32 `protobuf:"fixed32,8,opt,name=floa,proto3" json:"floa,omitempty"`
	Fixed3    uint32  `protobuf:"fixed32,10,opt,name=fixed3,proto3" json:"fixed3,omitempty"`
	Sadfsdf   uint64  `protobuf:"fixed64,11,opt,name=sadfsdf,proto3" json:"sadfsdf,omitempty"`
	Sdfsdfsdf int64   `protobuf:"fixed64,12,opt,name=sdfsdfsdf,proto3" json:"sdfsdfsdf,omitempty"`
	Sdfsadf   int64   `protobuf:"fixed64,23,opt,name=sdfsadf,proto3" json:"sdfsadf,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Student) GetP() int32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *Student) GetPp() int64 {
	if x != nil {
		return x.Pp
	}
	return 0
}

func (x *Student) GetPpp() int64 {
	if x != nil {
		return x.Ppp
	}
	return 0
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetNamess() []byte {
	if x != nil {
		return x.Namess
	}
	return nil
}

func (x *Student) GetDoub() float64 {
	if x != nil {
		return x.Doub
	}
	return 0
}

func (x *Student) GetFloa() float32 {
	if x != nil {
		return x.Floa
	}
	return 0
}

func (x *Student) GetFixed3() uint32 {
	if x != nil {
		return x.Fixed3
	}
	return 0
}

func (x *Student) GetSadfsdf() uint64 {
	if x != nil {
		return x.Sadfsdf
	}
	return 0
}

func (x *Student) GetSdfsdfsdf() int64 {
	if x != nil {
		return x.Sdfsdfsdf
	}
	return 0
}

func (x *Student) GetSdfsadf() int64 {
	if x != nil {
		return x.Sdfsadf
	}
	return 0
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0x85, 0x02, 0x0a, 0x07, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11, 0x52, 0x01, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x70, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x70, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x70, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x52, 0x03, 0x70,
	0x70, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x6f, 0x75, 0x62, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x64, 0x6f,
	0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x6f, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x66, 0x6c, 0x6f, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x61, 0x64, 0x66, 0x73, 0x64, 0x66, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x06, 0x52,
	0x07, 0x73, 0x61, 0x64, 0x66, 0x73, 0x64, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x64, 0x66, 0x73,
	0x64, 0x66, 0x73, 0x64, 0x66, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x10, 0x52, 0x09, 0x73, 0x64, 0x66,
	0x73, 0x64, 0x66, 0x73, 0x64, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x64, 0x66, 0x73, 0x61, 0x64,
	0x66, 0x18, 0x17, 0x20, 0x01, 0x28, 0x10, 0x52, 0x07, 0x73, 0x64, 0x66, 0x73, 0x61, 0x64, 0x66,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_proto_goTypes = []interface{}{
	(*Student)(nil), // 0: example.Student
}
var file_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
