// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: example.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type O1O2O3O3Enum int32

const (
	O1O2O3_LQF  O1O2O3O3Enum = 0
	O1O2O3_LQF1 O1O2O3O3Enum = 0
)

// Enum value maps for O1O2O3O3Enum.
var (
	O1O2O3O3Enum_name = map[int32]string{
		0: "LQF",
		// Duplicate value: 0: "LQF1",
	}
	O1O2O3O3Enum_value = map[string]int32{
		"LQF":  0,
		"LQF1": 0,
	}
)

func (x O1O2O3O3Enum) Enum() *O1O2O3O3Enum {
	p := new(O1O2O3O3Enum)
	*p = x
	return p
}

func (x O1O2O3O3Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (O1O2O3O3Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (O1O2O3O3Enum) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x O1O2O3O3Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use O1O2O3O3Enum.Descriptor instead.
func (O1O2O3O3Enum) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type O1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *O1) Reset() {
	*x = O1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *O1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*O1) ProtoMessage() {}

func (x *O1) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use O1.ProtoReflect.Descriptor instead.
func (*O1) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

type Users struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age        int32           `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Id         string          `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	RateDouble float64         `protobuf:"fixed64,4,opt,name=rate_double,json=rateDouble,proto3" json:"rate_double,omitempty"`
	RateFloat  float32         `protobuf:"fixed32,5,opt,name=rate_float,json=rateFloat,proto3" json:"rate_float,omitempty"`
	Goable     uint32          `protobuf:"fixed32,10,opt,name=goable,proto3" json:"goable,omitempty"`
	NameByte   []byte          `protobuf:"bytes,11,opt,name=name_byte,json=nameByte,proto3" json:"name_byte,omitempty"`
	Enum_Users O1O2O3O3Enum    `protobuf:"varint,13,opt,name=enum_Users,json=enumUsers,proto3,enum=models.O1O2O3O3Enum" json:"enum_Users,omitempty"`
	O1_Users   *O1             `protobuf:"bytes,12,opt,name=o1_Users,json=o1Users,proto3" json:"o1_Users,omitempty"`
	Map_Users  map[int32]int32 `protobuf:"bytes,14,rep,name=map_Users,json=mapUsers,proto3" json:"map_Users,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Any_Users  *anypb.Any      `protobuf:"bytes,35,opt,name=any_Users,json=anyUsers,proto3" json:"any_Users,omitempty"`
	// Types that are assignable to One:
	//	*Users_Allow
	//	*Users_Allow2
	One isUsers_One `protobuf_oneof:"one"`
}

func (x *Users) Reset() {
	*x = Users{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *Users) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Users) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Users) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Users) GetRateDouble() float64 {
	if x != nil {
		return x.RateDouble
	}
	return 0
}

func (x *Users) GetRateFloat() float32 {
	if x != nil {
		return x.RateFloat
	}
	return 0
}

func (x *Users) GetGoable() uint32 {
	if x != nil {
		return x.Goable
	}
	return 0
}

func (x *Users) GetNameByte() []byte {
	if x != nil {
		return x.NameByte
	}
	return nil
}

func (x *Users) GetEnum_Users() O1O2O3O3Enum {
	if x != nil {
		return x.Enum_Users
	}
	return O1O2O3_LQF
}

func (x *Users) GetO1_Users() *O1 {
	if x != nil {
		return x.O1_Users
	}
	return nil
}

func (x *Users) GetMap_Users() map[int32]int32 {
	if x != nil {
		return x.Map_Users
	}
	return nil
}

func (x *Users) GetAny_Users() *anypb.Any {
	if x != nil {
		return x.Any_Users
	}
	return nil
}

func (m *Users) GetOne() isUsers_One {
	if m != nil {
		return m.One
	}
	return nil
}

func (x *Users) GetAllow() string {
	if x, ok := x.GetOne().(*Users_Allow); ok {
		return x.Allow
	}
	return ""
}

func (x *Users) GetAllow2() string {
	if x, ok := x.GetOne().(*Users_Allow2); ok {
		return x.Allow2
	}
	return ""
}

type isUsers_One interface {
	isUsers_One()
}

type Users_Allow struct {
	Allow string `protobuf:"bytes,99,opt,name=allow,proto3,oneof"`
}

type Users_Allow2 struct {
	Allow2 string `protobuf:"bytes,100,opt,name=allow2,proto3,oneof"`
}

func (*Users_Allow) isUsers_One() {}

func (*Users_Allow2) isUsers_One() {}

type O1O2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *O1O2) Reset() {
	*x = O1O2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *O1O2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*O1O2) ProtoMessage() {}

func (x *O1O2) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use O1O2.ProtoReflect.Descriptor instead.
func (*O1O2) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0}
}

type O1O2O3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *O1O2O3) Reset() {
	*x = O1O2O3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *O1O2O3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*O1O2O3) ProtoMessage() {}

func (x *O1O2O3) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use O1O2O3.ProtoReflect.Descriptor instead.
func (*O1O2O3) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0, 0}
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x32, 0x0a, 0x02, 0x6f, 0x31, 0x1a, 0x2c, 0x0a, 0x02, 0x6f, 0x32, 0x1a, 0x26,
	0x0a, 0x02, 0x6f, 0x33, 0x22, 0x20, 0x0a, 0x07, 0x6f, 0x33, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x12,
	0x07, 0x0a, 0x03, 0x4c, 0x51, 0x46, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x51, 0x46, 0x31,
	0x10, 0x00, 0x1a, 0x02, 0x10, 0x01, 0x22, 0xf5, 0x03, 0x0a, 0x05, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x64,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x72, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x74, 0x65, 0x5f,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x61, 0x74,
	0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x6f, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x67, 0x6f, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x79, 0x74, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x65,
	0x6e, 0x75, 0x6d, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x6f, 0x31, 0x2e, 0x6f, 0x32, 0x2e, 0x6f,
	0x33, 0x2e, 0x6f, 0x33, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x6f, 0x31, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x6f, 0x31, 0x52, 0x07, 0x6f, 0x31, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x6d,
	0x61, 0x70, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x4d, 0x61,
	0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x61, 0x70,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x61, 0x6e, 0x79, 0x5f, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08,
	0x61, 0x6e, 0x79, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x18, 0x63, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x12, 0x18, 0x0a, 0x06, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x32, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x06, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x32, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x61,
	0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x32, 0x3e,
	0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2d, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x1a,
	0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_proto_goTypes = []interface{}{
	(O1O2O3O3Enum)(0), // 0: models.o1.o2.o3.o3_enum
	(*O1)(nil),        // 1: models.o1
	(*Users)(nil),     // 2: models.Users
	(*O1O2)(nil),      // 3: models.o1.o2
	(*O1O2O3)(nil),    // 4: models.o1.o2.o3
	nil,               // 5: models.Users.MapUsersEntry
	(*anypb.Any)(nil), // 6: google.protobuf.Any
}
var file_example_proto_depIdxs = []int32{
	0, // 0: models.Users.enum_Users:type_name -> models.o1.o2.o3.o3_enum
	1, // 1: models.Users.o1_Users:type_name -> models.o1
	5, // 2: models.Users.map_Users:type_name -> models.Users.MapUsersEntry
	6, // 3: models.Users.any_Users:type_name -> google.protobuf.Any
	2, // 4: models.SearchService.ServiceSearch:input_type -> models.Users
	2, // 5: models.SearchService.ServiceSearch:output_type -> models.Users
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*O1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Users); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*O1O2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*O1O2O3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_example_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Users_Allow)(nil),
		(*Users_Allow2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
